source_data_list:
  - OL

SB:
  mysql_conf:
    dbtable: testdb1.TRANSACTIONSYNC
    partition_column: App_Transaction_Id

OL:
  sftp_conf:
      filetype: csv
      delimiter: ','
      directory: /home/ubuntu/

s3_conf:
  s3_bucket: kundata



mongodb_config:
  database: school
  collection: students

redshift_conf:
  filetype: csv
  delimiter: |
  dbtable: PUBLIC.TXN_FCT
  query: SELECT txn_id, create_time, amount, cust_id from PUBLIC.TXN_FCT

