source_data_list:
  - addr

SB:
  mysql_conf:
    dbtable: testdb1.TRANSACTIONSYNC
    partition_column: App_Transaction_Id

OL:
  sftp_conf:
      filetype: csv
      delimiter: |
      directory: /home/ubuntu/
      filename: receipts_delta_GBR_14_10_2017.csv

CP:
  s3_conf:
    s3_bucket: kundata
    filename: KC_Extract_1_20171009.csv



addr:
  mongodb_config:
    database: customers
    collection: address

redshift_conf:
  filetype: csv
  delimiter: |
  dbtable: PUBLIC.TXN_FCT
  query: SELECT txn_id, create_time, amount, cust_id from PUBLIC.TXN_FCT

